DATA1 SEGMENT
	NUM1 DW 1234H
	NUM2 DB 0F2H
	RESULT DW 1 DUP (0)
DATA1 ENDS

CODE1 SEGMENT
	ASSUME CS: CODE1, DS: DATA1
	START: 
		MOV AX, DATA1
		MOV DS, AX
		MOV AX, NUM1
		DIV NUM2
		MOV RESULT, AL ;QUOTIENT
		MOV RESULT+1,AH ;REMAINDER
		MOV AH, 4CH
		INT 21H
CODE1 ENDS
END START